version: 2

jobs:
  lint:
    macos:
      xcode: "10.0.0"
    steps:
      - checkout
      - run:
          name: Install Swiftlint
          command: ./Scripts/install_swiftlint.sh
      - run:
          name: Lint
          command: swiftlint

  build-for-test:
    macos:
      xcode: "10.0.0"
    steps:
      - checkout
      - run:
          name: Install Dependencies
          command: ./Scripts/before_install.sh
      - run:
          name: Update Dependencies
          command: ./Scripts/update_dependencies.sh
      - run:
          name: Build for testing
          command: ./Scripts/build_for_testing.sh

  test-ipad-10-3-1:
    macos:
      xcode: "10.0.0"
    steps:
      - checkout
      - run:
          name: Run tests on iPad iOS 10.3.1
          command: ./Scripts/test_without_building.sh "10.3.1" "iPad Air 2"

  test-ipad-11-2:
    macos:
      xcode: "10.0.0"
    steps:
      - checkout
      - run:
          name: Run tests on iPad iOS 11.2
          command: ./Scripts/test_without_building.sh "11.2" "iPad Air 2"

  test-ipad-12-0:
    macos:
      xcode: "10.0.0"
    steps:
      - checkout
      - run:
          name: Run tests on iPad iOS 12.0
          command: ./Scripts/test_without_building.sh "12.0" "iPad Air 2"

  test-iphone5s-10-3-2:
    macos:
      xcode: "10.0.0"
    steps:
      - checkout
      - run:
          name: Run tests on iPhone iOS 10.3.1
          command: ./Scripts/test_without_building.sh "10.3.1" "iPhone 5s"

  test-iphone8-11-2:
    macos:
      xcode: "10.0.0"
    steps:
      - checkout
      - run:
          name: Run tests on iPhone iOS 11.2
          command: ./Scripts/test_without_building_coverage.sh "11.2" "iPhone 8"

  test-iphone-x-12-0:
    macos:
      xcode: "10.0.0"
    steps:
      - checkout
      - run:
          name: Run tests on iPhone (X series) iOS 12.0
          command: ./Scripts/test_without_building_coverage.sh "12.0" "iPhone XS"

  codecov:
    macos:
      xcode: "10.0.0"
    steps:
      - checkout  
      - run:
          name: Codecov
          command: bash <(curl -s https://codecov.io/bash) -J 'Rocket.Chat'

workflows:
  version: 2
  build-and-test:
    jobs:
      - lint:
         filters:
           branches:
             ignore:
               - /^docs[-\/].*$/
               - /^wip[-\/].*$/
               - /^.*-docs$/
               - /^.*-wip$/

      - test-ipad-10-3-1:
          requires:
            - lint

      - test-ipad-11-2:
          requires:
            - lint

      - test-ipad-12-0:
          requires:
            - lint

      - test-iphone5s-10-3-2:
          requires:
            - lint

      - test-iphone8-11-2:
          requires:
            - lint

      - test-iphone-x-12-0:
          requires:
            - lint

      - codecov:
          requires:
            - lint

