version: 2

jobs:
  lint:
    macos:
      xcode: "9.0"
    steps:
      - checkout
      - run:
          name: Install Swiftlint
          command: ./Scripts/install_swiftlint.sh
      - run:
          name: Lint
          command: swiftlint

  test:
    macos:
      xcode: "9.0"
    steps:
      - checkout
      - run:
          name: Update Dependencies
          command: ./Scripts/update_dependencies.sh
      - run:
          name: Run tests on iPad iOS 10.3
          command: ./Scripts/test-clean.sh "10.3.1" "iPad Air 2"
      - run:
          name: Run tests on iPhone iOS 10.3
          command: ./Scripts/test.sh "10.3.1" "iPhone 5"
      - run:
          name: Run tests on iPad iOS 11.0
          command: ./Scripts/test.sh "11.0" "iPad Air 2"
      - run:
          name: Run tests on iPhone iOS 11.0
          command: ./Scripts/test-coverage.sh "11.0" "iPhone 8"
      - run:
          name: Codecov
          command: bash <(curl -s https://codecov.io/bash) -J 'Rocket.Chat'

workflows:
  version: 2
  build-and-test:
    jobs:
      - lint:
         filters:
           branches:
             ignore:
               - /^docs[-\/].*$/
               - /^wip[-\/].*$/
               - /^.*-docs$/
               - /^.*-wip$/
      - test:
          requires:
            - lint

